import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import NodeEdgeProvider from "./providers/NodeEdgeProvider";
import JsonProvider from "./providers/JsonListsProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // todo: might want to check what is this warning, and if can be placed here or remove
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <AppSidebar />
          <NodeEdgeProvider>
            <JsonProvider>
              <SidebarInset>{children}</SidebarInset>
            </JsonProvider>
          </NodeEdgeProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
